# Generated by Django 2.1.8 on 2019-10-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_bsj_pact', models.CharField(max_length=556, verbose_name='bsjpact_data')),
                ('old_bb_pact', models.CharField(max_length=556, verbose_name='bbpact_data')),
                ('old_v3_pact', models.CharField(max_length=566, verbose_name='v3pact_data')),
                ('new_bsj_pact', models.CharField(max_length=556, verbose_name='bsjpact_data')),
                ('new_bb_pact', models.CharField(max_length=556, verbose_name='bbpact_data')),
                ('new_v3_pact', models.CharField(max_length=566, verbose_name='v3pact_data')),
            ],
        ),
    ]
