# Generated by Django 2.1.8 on 2019-10-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_datacheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacheck',
            options={'verbose_name': '校验', 'verbose_name_plural': '校验'},
        ),
    ]
